### ISSUE TITLE
Add new mosters

### ISSUE THREAD

**Issue by Himank101** [acmpesuecc/text-based-rpg#2]
The script currently has only 5 monsters. Add two more monsters with their own stats as you see fit.
Intial blocking time : 6 hrs [for first 6 hrs many people can try solving, multiple pr for this issue can be accepted]
Max block time : 45 mins

> **_NOTE:_**  Only for GUI2.py

**Comment by Himank101** [comment]
The script currently has only 5 monsters. Add two more monsters with their own stats as you see fit.

**Comment by Hiyanachnani** [comment]
can i get this issue assigned to me?
PES2202200178

**Comment by Tree1527** [comment]
Could i get this issue assigned to me?
Aditya Rajendra Shinde
PES2202200479

**Comment by Anjana-Rose** [comment]
Can I get this issue assigned to me 
PES2202200354

**Comment by tanishkapasarad** [comment]
can i work on this? tanishka pasarad

**Comment by mokshablr** [comment]
can i get assigned to this? Arjun R Maniyani

**Comment by BalajiRock** [comment]
can i work on this? Balaji M @Himank101

**Comment by mokshablr** [comment]
@Himank101 can i get this assigned to me?

**Comment by Sushh-24** [comment]
can i work on this @Himank101

**Comment by sruthiroyal28** [comment]
@Himank101 i would like to work this . can u assign it to me ??

**Comment by Tree1527** [comment]
Could I please work on this @Himank101

**Comment by Himank101** [comment]
Guyss
this is an open issue
no need to ask
just submit PRs
If they are feasible they will be merged

**Comment by AtharvaAnilChanda** [comment]
can i work on this?

**Comment by Himank101** [comment]
yeah sure

**Comment by siddarthpai** [comment]
hey can i work on this?

**Comment by its-abhishek** [comment]
i would work on this issue

**Comment by Keshav1105** [comment]
Can i work on this

**Comment by MaNameEJeff** [comment]
Can I work on this please :)

**Comment by Himank101** [comment]
this repo is issue is being closed due to too many responses coming in
