### ISSUE TITLE
HP of player going above 100 

### ISSUE THREAD

**Issue by AtharvaAnilChanda** [acmpesuecc/text-based-rpg#23]
Armor adds to hp leading to player's hp going above 100 

Case : Hp = 100 , Armor = orichalium and monster attack 30< 
Hp goes above 100  
Blocking time :15 mins

**Comment by Himank101** [comment]
!bounty 10

**Comment by Himank101** [comment]
@AtharvaAnilChanda Thank you for raising the issue! Appreciate the enthusiasm!

**Comment by Himank101** [comment]
!bounty 10

**Comment by its-abhishek** [comment]
i would work on this issue

**Comment by AtharvaAnilChanda** [comment]
on it

**Comment by MaNameEJeff** [comment]
Please can I work on this :)

**Comment by Vaarun-Kamath** [comment]
hey can i get this pls :)

**Comment by Himank101** [comment]
issue has been Atharva since he discovered the issue and has been solved

**Comment by Himank101** [comment]
!bounty 10
