### ISSUE TITLE
Add a boss Room

### ISSUE THREAD

**Issue by Himank101** [acmpesuecc/text-based-rpg#3]
Currently the game runs in an infinite loop. Make the loop terminate after passing through 10 rooms and go into the final boss room. You will be required to make a boss monster for the same

You'll need to make a function to call get_room() iteratively
and call the boss room function after that (you'll have to make this)
You'll also have to make your own get_monster() function specifically for this room.
Intial blocking time : 6 hrs [for first 6 hrs many people can try solving, multiple pr for this issue can be accepted]
Max block time : 2 -3 hrs
*Give updates every 30 mins
> **_NOTE:_**  Only for GUI2.py

**Comment by surajkadapa** [comment]
Can I be assigned to this issue?

**Comment by Himank101** [comment]
Sure! Go for it!

**Comment by surajkadapa** [comment]
My PRN is PES2202200348
