### ISSUE TITLE
Add a medium potion

### ISSUE THREAD

**Issue by Himank101** [acmpesuecc/text-based-rpg#4]
Add a medium potion that increases the players HP by 40 points and costs 450 Gold
should be sold in shop
Take the value of the number of medium sized potions in a global variable and construct a separate functions to handle calculations related to HP and Gold wherever required
> **_NOTE:_**  Only for GUI2.py

**Comment by sean-18** [comment]
@Himank101 can i get access to this issue
PES2UG21CS924
SEAN SOUGAIJAM

**Comment by Himank101** [comment]
sure!
