### ISSUE TITLE
Add more armors

### ISSUE THREAD

**Issue by Himank101** [acmpesuecc/text-based-rpg#5]
We currently have 3 types of armour. Add 2 more

Intial blocking time : 6 hrs [for first 6 hrs many people can try solving, multiple pr for this issue can be accepted]
Max block time : 45 mins

**Comment by Hiyanachnani** [comment]
can i get this issue assigned to me?
PES2202200178

**Comment by sphoorthiY** [comment]
can i work on this issue ??
PES2UG21CS241
SPHURTHI YANDAMURI

**Comment by ankithlemuel** [comment]
can i work on this
PES2UG21EC024

**Comment by tanishkapasarad** [comment]
can i work on this? tanishka pasarad

**Comment by Anjana-Rose** [comment]
Can I work on this?
PES2202200354

**Comment by V3D4NTH** [comment]
Hi! I want this to be assigned to me. I already have the code ready. PES2202200657

**Comment by Himank101** [comment]
this issue will be closed since there was already a PR. See #13

**Comment by Himank101** [comment]
The issue will be assigned to @Hiyanachnani first

**Comment by sruthiroyal28** [comment]
@Himank101 i would like to work on this . can u assign it to me??
PES2UG21CS620
Sruthi

**Comment by Sushh-24** [comment]
@Himank101 can i work on this PES2UG21CS560?

**Comment by sphoorthiY** [comment]
@Himank101 can i work on this 
PES2UG21CS241

**Comment by vrac10** [comment]
@Himank101  can i work on this 
PES2202200278

**Comment by Himank101** [comment]
Guyss
this is an open issue
no need to ask
just submit PRs
If they are feasible they will be merged

**Comment by its-abhishek** [comment]
i would work on this issue

**Comment by Himank101** [comment]
This issue is being closed due to too many responses
