### ISSUE TITLE
Add a boss monster

### ISSUE THREAD

**Issue by Himank101** [acmpesuecc/text-based-rpg#6]
Add a Boss monster. You are free to choose his stats

> **_NOTE:_**  Only for GUI2.py

**Comment by mayankpm** [comment]
@Himank101 can I get assigned to this issue? Thanks (Mayank PM)

**Comment by Himank101** [comment]
Go for it!

**Comment by Himank101** [comment]
Can you also mention your SRN?

**Comment by mayankpm** [comment]
PES2UG21CS932

**Comment by nik2203** [comment]
hi, can i be assigned to this issue
PES2UG21CS334

**Comment by Himank101** [comment]
@mayankpm Please provide an update on your progress

**Comment by siddarthpai** [comment]
please review my updated pr

**Comment by Tree1527** [comment]
Could I be assigned to this issue
Aditya Rajendra Shinde
PES2202200479

**Comment by sruthiroyal28** [comment]
@Himank101 i would like to work on this . can u assign this to me??
PES2UG21CS620
Y.Sruthi Royal

**Comment by Himank101** [comment]
There's an ongoing pull request. See #12
